### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Scouting2016#7]
- [x] Add popup when the form is submitted - 10 min
- [x] Add a button to set the IP -  5 min
- [x] Add a popup for the IP - 10 min
- [ ] Make a name variable - 5 min (Ask Jon on how people will be able to change)
- [ ] Add a lead scout form with URL - 20 min
- [ ]  Add lead scout functionality - 60 min

**Comment by ajusa** [comment]
Extra Stuff that Jon said
Add a way to identify which scout
Assign Scouting Positions
